apiVersion: apps/v1
kind: Deplotment 
metadata:
  name: jenkins-deployment
spec:
  selector:
    matchlabels:
      app: nginx
replicas: 1
template:
  metadata:
    labels:
      app: nginx
  spec:
    containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
  